from typing import List
from app.models.combo import ComboRequest, ComboRecommendation, CartContext
from app.models.recommendation import Meal
from app.services.combo.rules_engine import ComboRulesEngine
from app.services.combo.combo_scorer import ComboScorer

class ComboBuilder:
    def __init__(self):
        self.rules_engine = ComboRulesEngine()
        self.scorer = ComboScorer()

    def build_cart_suggestions(self, request: ComboRequest) -> List[ComboRecommendation]:
        if not request.context.cart_meals:
            return []

        # 1. Get baseline valid addons from rules
        valid_addons = self.rules_engine.get_valid_addons(request.context, request.candidate_meals)

        # 2. Score them
        recommendations = []
        for candidate, reason, base_score in valid_addons:
            final_score = self.scorer.score_addon(candidate, request.context, base_score)
            
            # If no reason was generated by rules, generate a generic one
            if not reason:
                if len(request.context.cart_meals) == 1:
                    reason = f"Frequently ordered with {request.context.cart_meals[0].name}."
                else:
                    reason = "Frequently ordered together with items in your cart."

            recommendations.append(
                ComboRecommendation(
                    meal=candidate,
                    match_score=final_score,
                    upsell_reason=reason
                )
            )

        # 3. Sort and truncate
        recommendations.sort(key=lambda x: x.match_score, reverse=True)
        return recommendations[:request.top_n]

    def build_single_upsell(self, target_meal: Meal, request: ComboRequest) -> List[ComboRecommendation]:
        """Convenience method for single item upsells."""
        # Temporarily override context to just be this single meal
        temp_context = CartContext(
            cart_meals=[target_meal],
            time_of_day=request.context.time_of_day,
            day_of_week=request.context.day_of_week,
            weather=request.context.weather,
            user_id=request.context.user_id
        )
        
        temp_request = ComboRequest(
            context=temp_context,
            candidate_meals=request.candidate_meals,
            top_n=request.top_n
        )
        return self.build_cart_suggestions(temp_request)
